# GitHub App Manifest
# This manifest configures a GitHub App with OAuth capabilities
# Reference: https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps-from-a-manifest

name: "OpenAI Integration"
description: "GitHub App for OpenAI integration with OAuth support"
url: "https://next-starter-template.pages.dev"

# Enable OAuth capabilities
# This is crucial for the app to appear in the OAuth list
request_oauth_on_install: true

# OAuth callback URL - required for OAuth flow
callback_url: "https://next-starter-template.pages.dev/api/auth/callback"

# OAuth scopes requested from users
default_permissions:
  # Repository permissions
  contents: read
  issues: write
  pull_requests: write
  metadata: read
  
  # Organization permissions (optional)
  # members: read

# User permissions for OAuth
user_permissions:
  # These are the permissions requested when a user authorizes the app
  email: read
  profile: read

# Webhook configuration (optional)
webhook_active: false

# Events the app subscribes to (if webhook is active)
default_events: []

# Public or private installation
public: false

# Redirect URL after installation
redirect_url: "https://next-starter-template.pages.dev/setup-complete"
