name: Incident
description: Track and resolve a production incident
title: "[INCIDENT] "
labels: ["incident"]
body:
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe user impact, start_time/end_time
      placeholder: |
        - Start time: YYYY-MM-DD HH:MM UTC
        - End time: YYYY-MM-DD HH:MM UTC (or "ongoing")
        - Users affected: 
        - Services affected:
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: Key events, logs, and links
      placeholder: |
        - HH:MM - Event description
        - HH:MM - Another event
        - Links to logs, dashboards, etc.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Mitigation/Next steps
      description: What was done to fix, and what's next
      placeholder: |
        Immediate mitigation:
        - Action taken
        
        Next steps:
        - [ ] Follow-up task
        - [ ] Post-mortem
    validations:
      required: true
