name: CF KillSwitch Triage
on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project to check"
        required: true
        type: choice
        options: [lgfc-staging, lgfc-prod]
        default: lgfc-staging

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN:  ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    steps:
      - name: Sanity — echo presence of env (values are masked)
        run: |
          echo "CF_API_TOKEN set? $([ -n "$CF_API_TOKEN" ] && echo yes || echo NO)"
          echo "CF_ACCOUNT_ID set? $([ -n "$CF_ACCOUNT_ID" ] && echo yes || echo NO)"
          if [ -z "$CF_API_TOKEN" ] || [ -z "$CF_ACCOUNT_ID" ]; then
            echo "::error::Missing CF secrets; add CF_API_TOKEN (Pages:Edit) and CF_ACCOUNT_ID"; exit 1; fi

      - name: Install wrangler + jq
        run: |
          npm i -g wrangler@^3
          wrangler --version
          sudo apt-get update -y && sudo apt-get install -y jq

      - name: Auth check (whoami) — if this fails, token scope/account is wrong
        run: |
          if ! wrangler whoami; then
            echo "::error::wrangler whoami failed → CF_API_TOKEN likely missing 'Account→Cloudflare Pages: Edit' or wrong account"; exit 2; fi

      - name: List Pages projects (auth + account wiring)
        run: |
          if ! wrangler pages project list | tee /tmp/projects.txt; then
            echo "::error::Failed to list Pages projects → token/account mismatch"; exit 3; fi

      - name: Verify requested project presence or create it
        run: |
          PROJ="${{ inputs.project }}"
          if ! grep -q "$PROJ" /tmp/projects.txt; then
            echo "Project $PROJ not found. Attempting creation…"
            if ! wrangler pages project create "$PROJ" --production-branch main; then
              echo "::error::Unable to create project '$PROJ' → token lacks Pages:Edit or wrong account"; exit 4; fi
          fi
          echo "::notice::Project $PROJ available."
