name: cf-pages (Next.js → next-on-pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Patch Next for Cloudflare
        run: npx @cloudflare/next-on-pages@latest

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PAGES_PROJECT || 'next-starter-template' }}
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
