name: Cloudflare Pages (Next.js → next-on-pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Adapt for Cloudflare Pages
        run: npx @cloudflare/next-on-pages@1.13.16

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PAGES_PROJECT || 'next-starter-template' }}
          directory: .vercel/output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
