name: CF Release (staging → production)
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: main
jobs:
  stage:
    uses: ./.github/workflows/pages-deploy.yml
    with:
      environment: staging
      branch: ${{ inputs.branch }}
  prod:
    needs: stage
    uses: ./.github/workflows/pages-deploy.yml
    with:
      environment: production
      branch: ${{ inputs.branch }}
