name: "Cloudflare Pages: rollback/promote by commit"

on:
  workflow_dispatch:
    inputs:
      target_sha:
        description: 'Specific commit SHA to promote (optional)'
        required: false
        default: ''
      days_ago:
        description: 'If target_sha not set, compute commit from this relative time (e.g. "2 weeks")'
        required: false
        default: '2 weeks'

permissions:
  contents: read

jobs:
  promote:
    name: Promote Cloudflare Pages deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve target SHA
        id: resolve
        run: |
          if [ -n "${{ github.event.inputs.target_sha }}" ] && [ "${{ github.event.inputs.target_sha }}" != "" ]; then
            echo "target_sha=${{ github.event.inputs.target_sha }}" >> $GITHUB_OUTPUT
          else
            git fetch origin main
            # compute commit before the asked time
            TARGET=$(git rev-list -n 1 --before="${{ github.event.inputs.days_ago }}" origin/main || true)
            if [ -z "$TARGET" ]; then
              echo "No commit found before '${{ github.event.inputs.days_ago }}' on origin/main" >&2
              exit 1
            fi
            echo "target_sha=$TARGET" >> $GITHUB_OUTPUT
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Promote/Restore Cloudflare deployment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          TARGET_SHA: ${{ steps.resolve.outputs.target_sha }}
        run: |
          echo "Resolved TARGET_SHA=$TARGET_SHA"
          chmod +x ./scripts/promote-cloudflare-deployment.sh
          ./scripts/promote-cloudflare-deployment.sh

      - name: Output done
        run: echo "Cloudflare promotion attempt complete. If it returned success, confirm in Cloudflare Pages UI."
