name: Docs Guardrails

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  docs_guardrails:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: pwd
