name: docs-secret-audit
on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (no deps needed; ensure repo is valid)
        run: npm ci --ignore-scripts || true

      - name: Run docs secret audit
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: npm run audit:docs
