name: Manual Deployment Orchestrator

on:
  workflow_dispatch:
    inputs:
      pr_or_issue_number:
        description: 'PR or Issue number to comment on (optional)'
        required: false
        type: string

jobs:
  orchestrate-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          if ! type -p gh >/dev/null; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          fi

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run deployment orchestrator
        run: |
          if [ -n "${{ inputs.pr_or_issue_number }}" ]; then
            ./scripts/deploy-orchestrator.sh "${{ inputs.pr_or_issue_number }}"
          else
            ./scripts/deploy-orchestrator.sh
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
